// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT79ciMsGg7a2WKvyz-IgCIgPaEmRziQc',
    appId: '1:840534652732:web:d2f2288b7b7493d2c19039',
    messagingSenderId: '840534652732',
    projectId: 'chat-app-feb15',
    authDomain: 'chat-app-feb15.firebaseapp.com',
    storageBucket: 'chat-app-feb15.appspot.com',
    measurementId: 'G-G2Y17770TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCeJZDKAobAcaZ5f9M9GIlzBLq4TTVnZ4',
    appId: '1:840534652732:android:a851748dc3a0adfec19039',
    messagingSenderId: '840534652732',
    projectId: 'chat-app-feb15',
    storageBucket: 'chat-app-feb15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgVw6CmSqWmvRO5E7_E2_aQ7li2IKTY8w',
    appId: '1:840534652732:ios:ff77a6123cbb7c74c19039',
    messagingSenderId: '840534652732',
    projectId: 'chat-app-feb15',
    storageBucket: 'chat-app-feb15.appspot.com',
    iosClientId: '840534652732-8h02tvmsvcb2f9ga1c2usm4s39neis85.apps.googleusercontent.com',
    iosBundleId: 'com.example.dimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgVw6CmSqWmvRO5E7_E2_aQ7li2IKTY8w',
    appId: '1:840534652732:ios:ff77a6123cbb7c74c19039',
    messagingSenderId: '840534652732',
    projectId: 'chat-app-feb15',
    storageBucket: 'chat-app-feb15.appspot.com',
    iosClientId: '840534652732-8h02tvmsvcb2f9ga1c2usm4s39neis85.apps.googleusercontent.com',
    iosBundleId: 'com.example.dimo',
  );
}
